version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    groups:
      deps-github-actions:
        patterns:
          - "*"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    groups:
      deps-devcontainers:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    groups:
      deps-maven-production:
        dependency-type: "production"
        patterns:
          - "*"
      deps-maven-dev:
        dependency-type: "development"
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.keycloak:*"
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
    groups:
      deps-npm-dev:
        dependency-type: "development"
        patterns:
          - "*"
