version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    groups:
      devcontainers:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    groups:
      maven-production:
        dependency-type: "production"
        patterns:
          - "*"
      maven-dev:
        dependency-type: "development"
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.keycloak:*"
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
    groups:
      npm-dev:
        dependency-type: "development"
        patterns:
          - "*"
