services:
  keycloak:
    environment:
      - KEYCLOAK_STARTUP
    depends_on:
      smtp:
        condition: service_started

  smtp:
    image: rnwood/smtp4dev:latest
    volumes:
      - smtpdata:/smtp4dev
    ports:
      - ${KEYCLOAK_EXPOSE}${SMTP4DEV_PORT}:80

volumes:
  smtpdata:
