services:
  keycloak:
    environment:
      - KC_DB_URL_HOST
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
      - KEYCLOAK_STARTUP
      - KC_BOOTSTRAP_ADMIN_USERNAME
      - KC_BOOTSTRAP_ADMIN_PASSWORD
      - KC_SPI_EVENTS_LISTENER_REDIS_EVENT_LISTENER_REDIS_URL=${REDIS_URL}
      - KC_HOSTNAME
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - SMTP_SERVER
    ports:
      - "${KEYCLOAK_EXPOSE}${KEYCLOAK_HTTP_PORT}:8080"
      - "${KEYCLOAK_EXPOSE}${KEYCLOAK_MANAGEMENT_PORT}:9000"
    depends_on:
      smtp:
        condition: service_started
    networks:
      # Needed to access Redis and PostgreSQL
      shared_network:

  smtp:
    image: rnwood/smtp4dev:latest
    volumes:
      - smtpdata:/smtp4dev
    ports:
      - ${KEYCLOAK_EXPOSE}${SMTP4DEV_PORT}:80
    networks:
      shared_network:

volumes:
  smtpdata:

networks:
  # This network allows access to shared services like MongoDB and Redis
  shared_network:
    name: ${COMMON_NET_NAME}
    external: true
