services:
  keycloak:
    image: ghcr.io/openfoodfacts/openfoodfacts-auth:${KEYCLOAK_TAG}

    environment:
      - KEYCLOAK_STARTUP
      - KC_BOOTSTRAP_ADMIN_USERNAME
      - KC_BOOTSTRAP_ADMIN_PASSWORD
      - KC_SPI_EVENTS_LISTENER_REDIS_EVENT_LISTENER_REDIS_URL=redis://${REDIS_URL}/0
      - KC_HOSTNAME=${KEYCLOAK_BASE_URL}
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - SMTP_SERVER
      - CLIENTS
    networks:
      default:

