services:
  keycloak:
    image: ghcr.io/openfoodfacts/openfoodfacts-auth:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KEYCLOAK_VERSION
    volumes:
      # Bind mount to theme folder so theme can be edited without rebuilding
      - ./theme/off:/opt/keycloak/themes/off

  keycloak_postgres:
    ports:
      - 5601:5432

  # Static web server to host dummy application
  test_client:
    image: nginx
    ports:
      - 5604:80
    volumes:
      - ./tests/client:/usr/share/nginx/html
