services:
  keycloak:
    image: ghcr.io/openfoodfacts/openfoodfacts-auth:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Bind mount to themes and runtime-scripts folders so they can be edited without rebuilding
      - ./theme/off:/opt/keycloak/themes/off
      - ./runtime-scripts:/opt/off

  # Static web server to host dummy application
  test_client:
    image: nginx
    ports:
      - 5604:80
    volumes:
      - ./tests/client:/usr/share/nginx/html
