services:
  test_keycloak:
    image: ghcr.io/openfoodfacts/openfoodfacts-auth:testcontainer
    build:
      context: ..
      dockerfile: Dockerfile
      target: testcontainer
    environment:
      - KC_SPI_EVENTS_LISTENER_REDIS_EVENT_LISTENER_REDIS_URL=${REDIS_URL}
      - KC_HOSTNAME=http://auth.openfoodfacts.localhost:5606
      - SMTP_SERVER=smtp
    ports:
      - "5606:8080"
    networks:
      # Needed to access Redis
      shared_network:

  # Static web server to host dummy application
  test_client:
    image: nginx
    ports:
      - 5604:80
    volumes:
      - ../tests/client:/usr/share/nginx/html

  smtp:
    image: rnwood/smtp4dev:latest
    volumes:
      - smtpdata:/smtp4dev
    ports:
      - ${KEYCLOAK_EXPOSE}${SMTP4DEV_PORT}:80
    networks:
      shared_network:

# Use a volume for smtpdev so it matches the dev project
volumes:
  smtpdata:

networks:
  # This network allows access to shared services like MongoDB and Redis
  shared_network:
    name: ${COMMON_NET_NAME}
    external: true
