name: Create and publish a Docker image

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=pr
            type=ref,event=branch
            type=sha,format=long

      - name: Prepare Docker build
        run: make pre_build

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm64
          build-args:
            KEYCLOAK_VERSION=${{ env.KEYCLOAK_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker testcontainer image
        uses: docker/build-push-action@v6
        with:
          context: .
          # TODO: Change this to !=
          push: ${{ github.event_name == 'pull_request' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-testcontainer
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-testcontainer,mode=max
          platforms: linux/amd64,linux/arm64
          target: testcontainer
          build-args:
            KEYCLOAK_VERSION=${{ env.KEYCLOAK_VERSION }}
          tags: |
            ghcr.io/openfoodfacts/openfoodfacts-auth:testcontainer
          labels: |
            org.opencontainers.image.version=testcontainer
          # Need to set the description via an annotation as this is a multi-arch image (https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images)
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Keycloak Image for integration testing using a pre-loaded realm and test clients in a dev-file database
      
